version: '3.1'

volumes:
  database_data:
    driver: local

services:
  db:
    build: .
    # image: db
    restart: always
    environment:
      POSTGRES_DB: merakidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5000:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    build: ../
    # image: web
    expose:
      - 8080
    ports:
      - 4004:4004
    volumes:
      - ./api:/usr/src/app/
    links:
      - db
#     networks:
#       - elk
# networks:
#   elk:
#     driver: bridge