version: '3.1'

volumes:
  database_data:
    driver: local

services:
  db:
    build: .
    # image: db
    hostname: db
    restart: always
    environment:
      POSTGRES_DB: merakidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5000:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - elk

  web:
    build: ../
    # image: web
    hostname: web
    expose:
      - 8080
    ports:
      - 4004:4004
    volumes:
      - ./api:/usr/src/app/
    links:
      - db
    networks:
      - elk

  pyapp:
    build: ../../Weapon_Detection/Tensorflow/models
    hostname: pyapp
    expose:
      - 5002
    ports:
      - 5002:5002
    links:
      - web
    #image: pyapp
    networks:
      - elk

  predictionapp:
    build: ../prediction/
    hostname: predictionapp
    ports:
      - 4100:4100
    links:
      - db
    #image: predictionapp
    networks:
      - elk
networks:
   elk:
     driver: bridge