version: '3.1'

volumes:
  database_data:
    driver: local

services:
  db:
    #build: .
    image: sonia679/merakipoc:databaseimage
    hostname: db
    restart: always
    environment:
      POSTGRES_DB: merakidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5000:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - elk

  web:
    #build: ../
    image: sonia679/merakipoc:middlewareimage
    hostname: web
    expose:
      - 4004
    ports:
      - 4004:4004
    volumes:
      - ./api:/usr/src/app/
    links:
      - db
    networks:
      - elk

  pyapp:
    #build: ../../Weapon_Detection/Tensorflow/models
    image: sonia679/merakipoc:objdetectionimage
    hostname: pyapp
    ports:
      - 5555:5555
    links:
      - web
    #image: pyapp
    networks:
      - elk

  predictionapp:
    #build: ../prediction/
    image: sonia679/merakipoc:predictionimage
    hostname: predictionapp
    ports:
      - 4100:4100
    links:
      - db
    #image: predictionapp
    networks:
      - elk
      
networks:
   elk:
     driver: bridge